// Default investor pipeline data — used when Supabase is not configured and localStorage is empty

export const DEFAULT_INVESTORS = [
  // ========== P1 — URGENT ==========
  { name:'Shapat (Partner)', fund:'White Whale Ventures', stage:'In Dialogue', priority:'P1', category:'VC — Warm', contact:'shapat@whitewhale.vc', intro:'Follow up on existing thread', emailDate:'', meetingDate:'', nextAction:'Send detailed deck + MIS this week. Ask for next meeting.', nextDate:'2026-03-20', notes:'Warm conversation already started. Shapat has hospitality background and showed active interest. Asked for more details. Warmest live VC lead. Most important live conversation — do NOT let this go cold.', ticketSize:'5–20 Cr', whyFit:'Warm conversation already started. Hospitality background, active interest.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now() },
  { name:'Partner (name TBC)', fund:'TDV Partners', stage:'In Dialogue', priority:'P1', category:'VC — Warm', contact:'Through existing contact', intro:'Send MIS immediately', emailDate:'', meetingDate:'', nextAction:'Send clean MIS this week. Follow up in 5 days.', nextDate:'2026-03-20', notes:'1 meeting done. Asked for MIS — positive diligence signal. They understand ops-heavy businesses. MIS request = genuine interest. Clean P&L, occupancy, unit economics.', ticketSize:'5–15 Cr', whyFit:'1 meeting done. Asked for MIS — positive diligence signal.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now()-1000 },
  { name:'Arjun Vaidya', fund:'V3 Ventures / Verlinvest India', stage:'Identified', priority:'P1', category:'Angel', contact:'linkedin.com/in/arjunvaidya · cal.com/arjun-vaidya-lec0j0', intro:'LinkedIn DM — he says "DM me, happy to chat"', emailDate:'', meetingDate:'', nextAction:'Send personalised LinkedIn DM this week. Lead with NUMA/Verlinvest angle.', nextDate:'2026-03-20', notes:'Most strategic angel. Runs V3 Ventures = Verlinvest India arm. Verlinvest backed NUMA (European KiwiStays). L Catterton hospitality background. 80+ portfolio cos. Last investment Dec 2025. Unlocks BOTH angel capital AND Verlinvest VC path.', ticketSize:'1–3 Cr', whyFit:'Runs V3 Ventures = Verlinvest India. Backed NUMA (European KiwiStays). Highest leverage move.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-2000 },
  { name:'Neetan Chopra', fund:'IndiGo Ventures', stage:'Identified', priority:'P1', category:'CVC — Travel Mandate', contact:'GoIndiGoVentures.com · Neetan Chopra on LinkedIn', intro:'Website + direct outreach to Neetan Chopra', emailDate:'', meetingDate:'', nextAction:'Draft pitch around IndiGo passenger journey → KiwiStays stays. Apply on website AND email Neetan.', nextDate:'2026-03-21', notes:'EXPLICIT mandate: travel + hospitality. ₹450Cr fund closed Jul 2025. 2 investments made — huge dry powder. IndiGo passengers fly to Goa/Dehradun and stay at KiwiStays. Distribution upside = massive. BIGGEST MISS found in research.', ticketSize:'5–20 Cr', whyFit:'Only fund with explicit hospitality mandate + fresh capital. Distribution partnership upside.', conflictCheck:'✅ None', fundStage:'Series A', updated:Date.now()-3000 },

  // ========== P2 — HIGH ==========
  { name:'Rishabh Mariwala', fund:'Sharrp Ventures', stage:'Identified', priority:'P2', category:'Family Office', contact:'sharrpventures.com/pitch · Rishabh Mariwala LinkedIn', intro:'Public pitch form + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Submit pitch form AND DM Rishabh on LinkedIn with 3-line hook.', nextDate:'2026-03-22', notes:'Marico family office. Portfolio: Mamaearth, boAt, SleepyCat, Bira, mCaffeine. COO of Sula Vineyards is now partner. 3 investments in last 12 months. Patient capital, no VC lifecycle pressure.', ticketSize:'5–20 Cr', whyFit:'Premium Indian consumer brand thesis = KiwiStays. Patient capital.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now()-4000 },
  { name:'Vikram Vaidyanathan', fund:'Z47 (formerly Matrix Partners India)', stage:'Identified', priority:'P2', category:'VC — Consumer Brand', contact:'namaste@z47.com · z47.com · Vikram LinkedIn', intro:'Email namaste@z47.com + LinkedIn to Vikram', emailDate:'', meetingDate:'', nextAction:'Lead with Stanza Living parallel. Email + LinkedIn.', nextDate:'2026-03-22', notes:'Backed Stanza Living at seed — managed accommodation, ops-heavy, exact model DNA. Also backed Country Delight, DaMENSCH. Fund IV = ₹4,500 Cr. Very founder-friendly culture.', ticketSize:'5–25 Cr', whyFit:'Backed Stanza Living (managed accommodation). Exact model DNA as KiwiStays.', conflictCheck:'✅ None', fundStage:'Series A', updated:Date.now()-5000 },
  { name:'Abhay Pandey / Gautam Mago', fund:'A91 Partners', stage:'Identified', priority:'P2', category:'VC — Consumer Growth', contact:'a91partners.com · Abhay Pandey LinkedIn', intro:'LinkedIn to deal leads who worked Blue Tokai', emailDate:'', meetingDate:'', nextAction:'Find who led Blue Tokai deal at A91 — that person is the door. Lead with "Blue Tokai of hospitality."', nextDate:'2026-03-23', notes:'Backed Blue Tokai (ops-heavy premium offline brand), Spacewood, Atomberg. $665M Fund III closed Apr 2025. May need stronger revenue first but worth planting seed now.', ticketSize:'15–40 Cr', whyFit:'Blue Tokai lead = ops-heavy premium offline brand thesis. $665M fresh fund.', conflictCheck:'✅ None', fundStage:'Series A / B', updated:Date.now()-6000 },
  { name:'Hariharan Premkumar', fund:'Anicut Capital', stage:'Identified', priority:'P2', category:'VC — Consumer Brand', contact:'anicuts.com · Hariharan LinkedIn', intro:'Direct application + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Apply directly via website AND LinkedIn. Lead with Blue Tokai/managed-ops thesis.', nextDate:'2026-03-22', notes:'Co-invested Blue Tokai Series B AND C. Consumer brand focus. Chennai-based, less gatekept. Clear submission process. More accessible than A91.', ticketSize:'5–20 Cr', whyFit:'Co-invested Blue Tokai = gets premium offline consumer brands.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now()-7000 },
  { name:'Gaurav Burman', fund:'Burman Family Holdings', stage:'Identified', priority:'P2', category:'Family Office', contact:'Gaurav Burman LinkedIn · burmanfamilyholdings.com', intro:'LinkedIn direct to Gaurav Burman', emailDate:'', meetingDate:'', nextAction:'Lead with Isprava angle: supply side → management layer.', nextDate:'2026-03-23', notes:'Dabur family investment arm. Backed Isprava (luxury second homes in Goa/Alibaug) at $130M growth round. RISK: Isprava owns Lohono Stays which is a DIRECT managed villa competitor. Proceed with caution.', ticketSize:'3–15 Cr', whyFit:'Backed Isprava — knows luxury Goa villas from developer side. KiwiStays = management layer.', conflictCheck:'⚠️ RISKY — Isprava owns Lohono Stays (direct managed villa competitor)', fundStage:'Seed / Series A', updated:Date.now()-8000 },
  { name:'Arjun Vaidya → Lopo Champalimaud', fund:'Verlinvest / V3 Ventures', stage:'Identified', priority:'P2', category:'VC — International', contact:'v3.ventures · verlinvest.com', intro:'Via Arjun Vaidya angel relationship first', emailDate:'', meetingDate:'', nextAction:'DO NOT cold email Verlinvest. Get Arjun Vaidya on board first — he becomes internal champion.', nextDate:'2026-03-25', notes:'Backed NUMA (European managed apartment startup — identical model). Backed Blue Tokai. India arm = V3 Ventures. Two-stage strategy: Arjun angel first → institutional Verlinvest round.', ticketSize:'10–30 Cr', whyFit:'NUMA = KiwiStays. Once Arjun is in, institutional round becomes very possible.', conflictCheck:'✅ None', fundStage:'Series A', updated:Date.now()-9000 },
  { name:'Mayank Jain / Alok Goyal', fund:'Stellaris Venture Partners', stage:'Identified', priority:'P2', category:'VC — Consumer Tech', contact:'stellarisvp.com · Mayank Jain LinkedIn', intro:'Apply via website + LinkedIn to Mayank Jain', emailDate:'', meetingDate:'', nextAction:'Lead with Peeko parallel: fragmented, trust deficit, offline-first. DM Mayank Jain.', nextDate:'2026-03-22', notes:'Led Peeko seed (Aug 2025) — ops-heavy, fragmented market. Backed Mamaearth, Zouk, Nestasia. $300M Fund III closed Nov 2024.', ticketSize:'3–15 Cr', whyFit:'Peeko thesis (fragmented, unbranded, attractive margins) = identical to KiwiStays.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now()-10000 },
  { name:'Maninder Gulati', fund:'Angel (ex-OYO CSO)', stage:'Identified', priority:'P2', category:'Angel', contact:'Maninder Gulati LinkedIn', intro:'LinkedIn DM — reachable post-Peeko visibility', emailDate:'', meetingDate:'', nextAction:'Lead with OYO angle: strategy for largest managed hospitality → KiwiStays taking it premium. Ask for 20 mins.', nextDate:'2026-03-22', notes:'Built strategy at OYO — knows managed accommodation, property owner dynamics intimately. Just backed Peeko (Aug 2025) — actively deploying. His backing = signal to property owners.', ticketSize:'1–3 Cr', whyFit:'Ex-OYO CSO. Knows managed hospitality better than any angel. Credibility signal.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-11000 },
  { name:'Mukesh Bansal', fund:'Angel (Myntra / Cult.fit)', stage:'Identified', priority:'P2', category:'Angel', contact:'Mukesh Bansal LinkedIn', intro:'LinkedIn DM', emailDate:'', meetingDate:'', nextAction:'Lead with Cult.fit parallel: offline, premium, experience-led, ops-heavy. Ask for 20 mins.', nextDate:'2026-03-22', notes:'Built Cult.fit — offline, ops-heavy, premium consumer experience across 200+ centres. Exact DNA match. Co-invests with Arjun Vaidya frequently. Backed FirstClub (Dec 2024) — actively writing cheques.', ticketSize:'1–3 Cr', whyFit:'Cult.fit = strongest operational parallel. Offline, premium, experience-led, ops-heavy.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-12000 },
  { name:'Neil Bahal', fund:'Negen Capital / Negen Angel Fund', stage:'Identified', priority:'P2', category:'Angel Fund — Consumer', contact:'negenaif.com · Neil Bahal LinkedIn', intro:'LinkedIn DM + Negen Angel Fund application', emailDate:'', meetingDate:'', nextAction:'Lead with Blue Tokai parallel — he backed Blue Tokai AND Burma Burma.', nextDate:'2026-04-02', notes:'Founder of Negen Capital (PMS) + Negen Angel Fund (AIF). Portfolio: Blue Tokai, Burma Burma, Burger Singh. Thesis: tech-enabled, consumer-facing brands. STRONGEST thesis match among angel funds.', ticketSize:'1–5 Cr', whyFit:'Blue Tokai + Burma Burma in portfolio = already believes in premium offline consumer brands with ops complexity.', conflictCheck:'✅ None', fundStage:'Seed / Pre-Series A', updated:Date.now()-12500 },
  { name:'V3 Ventures Team', fund:'V3 Ventures (Hosteller investor)', stage:'Identified', priority:'P2', category:'VC — Hospitality', contact:'v3.ventures', intro:'Via Arjun Vaidya angel relationship', emailDate:'', meetingDate:'', nextAction:'NOTE: V3 led Hosteller Series A. Approach via Arjun Vaidya path.', nextDate:'2026-03-22', notes:'Led The Hosteller Series A (₹32Cr equity, Sep 2024). V3 = Verlinvest India arm run by Arjun Vaidya. Hosteller = budget backpacker hostels. KiwiStays = premium villas. Different segments but same managed-stays thesis.', ticketSize:'5–20 Cr', whyFit:'Led Hosteller Series A + backed NUMA. Deepest hospitality thesis of any VC.', conflictCheck:'⚠️ Hosteller in portfolio — budget segment. Must clearly articulate premium differentiation.', fundStage:'Seed / Series A', updated:Date.now()-12800 },

  // ========== P3 — MEDIUM ==========
  { name:'Varun Alagh', fund:'Angel (Mamaearth / Honasa)', stage:'Identified', priority:'P3', category:'Angel', contact:'Varun Alagh LinkedIn', intro:'LinkedIn — active and reachable', emailDate:'', meetingDate:'', nextAction:'Short message. Lead with: ops-heavy premium consumer brand, 85 properties, profitable. Ask for 20 mins.', nextDate:'2026-03-25', notes:'73 portfolio companies. Last investment Feb 2026 — most actively deploying capital. Built Mamaearth = ops-heavy premium consumer brand at scale.', ticketSize:'1–3 Cr', whyFit:'Most actively deploying. Feb 2026 = writing cheques right now.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-13000 },
  { name:'Aman Gupta', fund:'Angel (boAt / Offbeat Studios)', stage:'Identified', priority:'P3', category:'Angel', contact:'@boatxaman on Instagram', intro:'Instagram DM @boatxaman', emailDate:'', meetingDate:'', nextAction:'Lead with Offbeat Studios: "You\'re building in travel. We manage what your audience stays in." 3 lines.', nextDate:'2026-03-25', notes:'Building Offbeat Studios = travel/content company. 11 investments in last 12 months. Backs lifestyle consumer brands. Instagram DM works — he responds to founders.', ticketSize:'1–3 Cr', whyFit:'Offbeat Studios = travel/content. More than generic angel pitch.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-14000 },
  { name:'Padmaja Ruparel', fund:'Indian Angel Network (IAN)', stage:'Identified', priority:'P3', category:'Angel Platform', contact:'indianangelnetwork.com · Padmaja Ruparel LinkedIn', intro:'Apply at indianangelnetwork.com', emailDate:'', meetingDate:'', nextAction:'Apply formally. Ask to connect with hospitality-focused member angels.', nextDate:'2026-03-24', notes:'Explicitly lists HOSPITALITY as investment sector. Backed Brevistay. IAN Alpha Fund closed at $100M Dec 2025 — fresh capital. 22 investments in 2025.', ticketSize:'3–8 Cr (assembled)', whyFit:'Only platform with genuine hospitality thesis. IAN already speaks the language.', conflictCheck:'✅ None', fundStage:'Seed', updated:Date.now()-15000 },
  { name:'Nandini Mansinghka', fund:'Mumbai Angels', stage:'Identified', priority:'P3', category:'Angel Platform', contact:'mumbaiangels.net', intro:'Apply via mumbaiangels.net', emailDate:'', meetingDate:'', nextAction:'Apply, then request intro to members with travel/hospitality background.', nextDate:'2026-03-26', notes:'700+ HNI investors across 60 cities. Premium consumer portfolio (Vahdam, Purplle, Fitpass). Slower process (60–90 days) but premium base.', ticketSize:'5–15 Cr (assembled)', whyFit:'Premium HNI base. Some members are likely KiwiStays property owner profile.', conflictCheck:'✅ None', fundStage:'Seed', updated:Date.now()-16000 },
  { name:'Kanwaljit Singh / Vinay Singh', fund:'Fireside Ventures', stage:'Identified', priority:'P3', category:'VC — Consumer', contact:'firesideventures.com · Kanwaljit Singh LinkedIn', intro:'Apply at firesideventures.com', emailDate:'', meetingDate:'', nextAction:'Pitch as "India\'s first premium travel experience brand." Expect "not our model" pushback.', nextDate:'2026-03-26', notes:'India\'s largest pure consumer brand fund. ₹5,300 Cr AUM. Fund IV just closed. CAVEAT: entire portfolio is product brands. KiwiStays is service/experience brand.', ticketSize:'5–20 Cr', whyFit:'Largest consumer brand fund. But potential model mismatch — service vs product.', conflictCheck:'⚠️ Check', fundStage:'Series A', updated:Date.now()-17000 },
  { name:'GC India Team', fund:'General Catalyst India', stage:'Identified', priority:'P3', category:'VC — Global / India', contact:'generalcatalyst.com', intro:'Apply via generalcatalyst.com/india', emailDate:'', meetingDate:'', nextAction:'Lead with Pronto parallel: formalising offline domestic services → premium vacation rentals.', nextDate:'2026-03-27', notes:'Committed $5Bn to India. Backed Pronto (ops-heavy offline home services — exact same thesis). India arm = ex-Venture Highway team.', ticketSize:'5–25 Cr', whyFit:'Backed Pronto = formalising India offline services market. $5Bn India commitment.', conflictCheck:'✅ None', fundStage:'Series A', updated:Date.now()-18000 },
  { name:'Partners (Mumbai-based)', fund:'Epiq Capital', stage:'Identified', priority:'P3', category:'VC — India Growth', contact:'epiqcapital.com', intro:'Apply via epiqcapital.com + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Lead with Pronto Series B. BUT: typically enter at Series B. Keep warm for next round.', nextDate:'2026-03-28', notes:'Led Pronto $25M Series B (Mar 2026). Portfolio: Zepto, Lenskart, Cult.fit. Typically invest $10-20M at Series B stage.', ticketSize:'10–25 Cr', whyFit:'Led Pronto Series B. Same thesis. But typically Series B entry.', conflictCheck:'✅ None', fundStage:'Series B', updated:Date.now()-19000 },
  { name:'Binny Bansal', fund:'Angel (Flipkart Co-founder)', stage:'Identified', priority:'P3', category:'Angel', contact:'Binny Bansal LinkedIn', intro:'LinkedIn — moderately accessible', emailDate:'', meetingDate:'', nextAction:'Lower priority than Mukesh/Maninder. Approach after Tier 1-2 anchors confirmed.', nextDate:'2026-03-28', notes:'Backed FirstClub (Dec 2024 seed). 9 investments in past 12 months — actively deploying. Less direct thesis fit but strong credibility signal on cap table.', ticketSize:'1–3 Cr', whyFit:'Cap table credibility signal to VCs. Not thesis-driven but adds credibility.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-20000 },
  { name:'Abhishek Goyal', fund:'Angel (Tracxn Co-founder)', stage:'Identified', priority:'P3', category:'Angel', contact:'Abhishek Goyal LinkedIn', intro:'LinkedIn', emailDate:'', meetingDate:'', nextAction:'Lower priority. Approach only if round has remaining capacity.', nextDate:'2026-04-01', notes:'Backed Peeko seed (Aug 2025). Data and SaaS background primarily. Less thesis fit but active angel. Network angel — useful for intros.', ticketSize:'0.5–1 Cr', whyFit:'Network angel. Useful for introductions more than conviction capital.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-21000 },
  { name:'Karthik Reddy / Sajith Pai', fund:'Blume Ventures', stage:'Identified', priority:'P3', category:'VC — Early Stage', contact:'blume.vc · Karthik Reddy LinkedIn', intro:'Email + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Lead with goSTOPS parallel — they led goSTOPS Series A (₹35Cr, Mar 2025). Prove KiwiStays is premium version.', nextDate:'2026-03-25', notes:'Led goSTOPS Series A (₹35Cr, Mar 2025) — micro-hospitality, asset-light, travel. Also early Zostel backer. India-first thesis. Strongest VC signal from India hospitality space.', ticketSize:'2–10 Cr', whyFit:'Led goSTOPS Series A. Already has hospitality thesis. Knows managed accommodation model.', conflictCheck:'⚠️ goSTOPS portfolio — budget hostel, NOT premium villa.', fundStage:'Seed / Series A', updated:Date.now()-27000 },
  { name:'Sanjay Mehta / Sumesh Menon', fund:'Lead Angels Network', stage:'Identified', priority:'P3', category:'Angel Platform', contact:'leadangels.in', intro:'Apply via leadangels.in', emailDate:'', meetingDate:'', nextAction:'Apply. Mention goSTOPS success as thesis validation for managed stays category.', nextDate:'2026-03-27', notes:'Mumbai-based angel network. Invested in goSTOPS pre-Series A AND Series A. Travel thesis proven. IIT Bombay alumni-driven.', ticketSize:'1–5 Cr (assembled)', whyFit:'Invested in goSTOPS across rounds. Proven travel/hospitality thesis.', conflictCheck:'⚠️ goSTOPS in portfolio — budget, not premium.', fundStage:'Seed', updated:Date.now()-28000 },
  { name:'Nikhil Kamath / Abhijeet Pai', fund:'Gruhas Capital', stage:'Identified', priority:'P3', category:'VC — PropTech/Consumer', contact:'gruhas.com', intro:'Apply via gruhas.com + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Position as PropTech + consumer experience play.', nextDate:'2026-03-28', notes:'Co-founded by Nikhil Kamath (Zerodha). $650M+ AUM across PropTech and consumer funds. 63 investments in 5 years.', ticketSize:'3–15 Cr', whyFit:'PropTech + consumer crossover. Nikhil Kamath = massive signal value on cap table.', conflictCheck:'✅ None', fundStage:'Pre-Series A / Series A', updated:Date.now()-30000 },
  { name:'T.V. Mohandas Pai', fund:'Aarin Capital', stage:'Identified', priority:'P3', category:'VC — Multi-sector', contact:'aarincapital.com', intro:'Apply via website + LinkedIn', emailDate:'', meetingDate:'', nextAction:'Position around hospitality vertical (4% of their portfolio).', nextDate:'2026-03-28', notes:'Bangalore-based fund led by TV Mohandas Pai (ex-Infosys CFO). Dedicated hospitality vertical though small. 18 consumer investments.', ticketSize:'3–10 Cr', whyFit:'Has dedicated hospitality vertical. 18 consumer investments.', conflictCheck:'✅ None', fundStage:'Seed / Series A', updated:Date.now()-31000 },
  { name:'Aryaman Vikram Birla', fund:'Aditya Birla Ventures', stage:'Identified', priority:'P3', category:'CVC — Consumer/Hospitality', contact:'adityabirlaventures.com · Aryaman Vikram Birla LinkedIn', intro:'Apply via adityabirlaventures.com + LinkedIn to Aryaman', emailDate:'', meetingDate:'', nextAction:'Position as consumer brand in hospitality.', nextDate:'2026-04-05', notes:'Founded by Aryaman Vikram Birla. Portfolio: Mokobara, Giva, Eka.Care. Also runs ABNAH — operates Hakkasan, Yauatcha.', ticketSize:'3–15 Cr', whyFit:'Aryaman runs both a consumer VC fund AND a hospitality operating company.', conflictCheck:'✅ None', fundStage:'Pre-Series A / Series A', updated:Date.now()-31500 },

  // ========== P4 — LATER ==========
  { name:'Sumir Chadha / Sandeep Singhal', fund:'WestBridge Capital', stage:'Identified', priority:'P4', category:'VC — Growth PE', contact:'westbridge.vc', intro:'Warm intro only at this stage', emailDate:'', meetingDate:'', nextAction:'Plant seed by sharing updates. Reach at Series B.', nextDate:'2026-04-15', notes:'Backed Third Wave Coffee Series B + C. Deep consumer conviction. Typical cheque = $20–50M+. Too large for current round.', ticketSize:'50–150 Cr', whyFit:'Deep consumer conviction. But cheque too large for current round.', conflictCheck:'✅ None', fundStage:'Series B+', updated:Date.now()-22000 },
  { name:'Ankur Warikoo', fund:'Angel (Nearbuy Founder)', stage:'Identified', priority:'P4', category:'Angel', contact:'Ankur Warikoo LinkedIn', intro:'LinkedIn / Newsletter', emailDate:'', meetingDate:'', nextAction:'Accessible but smaller cheque. Approach after Tier 1-2 anchors in.', nextDate:'2026-04-10', notes:'Built Nearbuy = experiences/hospitality marketplace. Actively angel invests. Understands India travel consumer. Very accessible.', ticketSize:'0.5–2 Cr', whyFit:'Nearbuy = hospitality marketplace. Good credibility signal.', conflictCheck:'✅ None', fundStage:'Angel', updated:Date.now()-23000 },
  { name:'Ankur Mittal', fund:'Inflection Point Ventures (IPV)', stage:'Identified', priority:'P4', category:'Angel Platform', contact:'ipventures.in', intro:'ipventures.in', emailDate:'', meetingDate:'', nextAction:'Use AFTER lead investor confirmed. Good for filling round quickly.', nextDate:'2026-04-15', notes:'Most active by volume (45 investments in 2025). Fast process. Sector agnostic. Speed is the value.', ticketSize:'1–3 Cr (assembled)', whyFit:'Fast capital for round fill. Not thesis-driven.', conflictCheck:'✅ None', fundStage:'Seed', updated:Date.now()-24000 },
  { name:'Hari Gopalakrishnan', fund:'Creaegis', stage:'Identified', priority:'P4', category:'VC — Later Stage', contact:'creaegis.com', intro:'Warm intro only', emailDate:'', meetingDate:'', nextAction:'Series C target. Keep on radar.', nextDate:'2026-05-01', notes:'Led Third Wave Coffee Series C ($35M). PE firm comfortable with offline consumer. Entry point = Series C.', ticketSize:'100–300 Cr', whyFit:'Premium offline consumer PE. Right investor for much larger round.', conflictCheck:'✅ None', fundStage:'Series C+', updated:Date.now()-25000 },
  { name:'Barath Shankar Subramanian', fund:'Accel India', stage:'Identified', priority:'P4', category:'VC — Tech First', contact:'accel.com · Barath Shankar LinkedIn', intro:'accel.com/companies — apply or warm intro', emailDate:'', meetingDate:'', nextAction:'Only approach if tech narrative is stronger. Otherwise skip for now.', nextDate:'2026-04-15', notes:'No vacation rental conflict. Backed FirstClub. $650M Fund VIII active. BUT: tech-first mandate.', ticketSize:'10–25 Cr', whyFit:'Good fund but will ask tech moat question hard.', conflictCheck:'✅ None', fundStage:'Series A', updated:Date.now()-26000 },
  { name:'Teruhide Sato', fund:'BEENEXT', stage:'Identified', priority:'P4', category:'VC — Singapore/India', contact:'beenext.com', intro:'Apply via beenext.com', emailDate:'', meetingDate:'', nextAction:'Lower priority — primarily fintech/SaaS focus.', nextDate:'2026-04-10', notes:'Singapore-based, very active in India early-stage. $160M fund. 261 portfolio cos. BUT: primarily fintech, e-commerce, SaaS.', ticketSize:'1–5 Cr', whyFit:'Active India early-stage investor. But no hospitality thesis.', conflictCheck:'✅ None', fundStage:'Seed / Pre-Series A', updated:Date.now()-32000 },

  // ========== CONFLICTS (DO NOT APPROACH) ==========
  { name:'Eudora Ventures', fund:'⛔ CONFLICT — Lohono Stays', stage:'Passed', priority:'P4', category:'CONFLICT', contact:'DO NOT CONTACT', intro:'N/A', emailDate:'', meetingDate:'', nextAction:'DO NOT APPROACH — direct competitor investor.', nextDate:'', notes:'⛔ HARD CONFLICT: Led Lohono Stays Series A ($4.69M, Mar 2022). Lohono = premium managed villa competitor.', ticketSize:'N/A', whyFit:'CONFLICT — invested in direct competitors.', conflictCheck:'⛔ HARD CONFLICT', fundStage:'N/A', updated:Date.now()-40000 },
  { name:'Anand Piramal', fund:'⛔ CONFLICT — Isprava/Lohono', stage:'Passed', priority:'P4', category:'CONFLICT', contact:'DO NOT CONTACT', intro:'N/A', emailDate:'', meetingDate:'', nextAction:'DO NOT APPROACH — led Isprava/Lohono early round.', nextDate:'', notes:'⛔ HARD CONFLICT: Led Isprava/Lohono Stays early funding round.', ticketSize:'N/A', whyFit:'CONFLICT — backed Isprava/Lohono.', conflictCheck:'⛔ HARD CONFLICT', fundStage:'N/A', updated:Date.now()-41000 },
  { name:'JSW Ventures', fund:'⛔ CONFLICT — StayVista', stage:'Passed', priority:'P4', category:'CONFLICT', contact:'DO NOT CONTACT', intro:'N/A', emailDate:'', meetingDate:'', nextAction:'DO NOT APPROACH — led StayVista Series B (₹40Cr, Jun 2025).', nextDate:'', notes:'⛔ HARD CONFLICT: Led StayVista Series B (₹40Cr, Jun 2025). StayVista = luxury villa/homestay rental platform.', ticketSize:'N/A', whyFit:'CONFLICT — lead investor in StayVista.', conflictCheck:'⛔ HARD CONFLICT', fundStage:'N/A', updated:Date.now()-42000 },
  { name:'DSG Consumer Partners', fund:'⛔ CONFLICT — StayVista', stage:'Passed', priority:'P4', category:'CONFLICT', contact:'DO NOT CONTACT', intro:'N/A', emailDate:'', meetingDate:'', nextAction:'DO NOT APPROACH — StayVista Series A investor since 2020.', nextDate:'', notes:'⛔ HARD CONFLICT: Series A investor in StayVista since 2020. Followed on in Series B.', ticketSize:'N/A', whyFit:'CONFLICT — long-term StayVista backer.', conflictCheck:'⛔ HARD CONFLICT', fundStage:'N/A', updated:Date.now()-43000 },
  { name:'Capri Global Family Office', fund:'⛔ CONFLICT — StayVista', stage:'Passed', priority:'P4', category:'CONFLICT', contact:'DO NOT CONTACT', intro:'N/A', emailDate:'', meetingDate:'', nextAction:'DO NOT APPROACH — participated in StayVista Series B.', nextDate:'', notes:'⛔ HARD CONFLICT: Participated in StayVista Series B (Jun 2025).', ticketSize:'N/A', whyFit:'CONFLICT — StayVista Series B participant.', conflictCheck:'⛔ HARD CONFLICT', fundStage:'N/A', updated:Date.now()-44000 },
];

export const DEFAULT_MESSAGES = [
  {
    investor: 'Shweta Tripathi — V3 Ventures',
    channel: 'LinkedIn DM',
    status: 'Ready',
    subject: '',
    body: `Hi Shweta,

Thanks for connecting! I'm Nymisha — CA, IIM-B, co-founder of KiwiStays. We're building India's first managed brand for vacation rentals in the ₹1K–4K/night segment — where 70% of India actually books, but no managed player exists.

61 properties, 78% occupancy, EBITDA-positive, zero external funding. AI-driven ops give us a structural cost advantage that luxury PMCs can't replicate at their price point.

Raising ₹10Cr Pre-Series A. Would love 20 minutes — happy to share a deck beforehand.`,
    notes: 'P1 — Shweta is Consumer Investor at V3, screens deals for Arjun Vaidya. Ex-WEH Ventures. Send this first before/alongside the Arjun DM so the deal lands warm.',
    updated: Date.now()
  },
  {
    investor: 'Arjun Vaidya — V3 Ventures / Verlinvest',
    channel: 'LinkedIn DM',
    status: 'Ready',
    subject: '',
    body: `Hi Arjun,

I'm Nymisha — CA, IIM-B, ex-IAN, new mom, co-founder of KiwiStays. My son's name is Arjun — so you're my lucky first outreach.

You've backed managed stays in Europe and budget travel in India. We're building the piece in between — mid-premium vacation rentals at ₹1K-4K/night, where 70% of India actually books but no managed brand exists. 61 properties, 78% occupancy, contribution-positive, no external funding yet.

Raising ₹10Cr Pre-Series A. Accelerant, not oxygen.

Would love 20 minutes. Happy to work around your schedule.

Nymisha Puvvada
Co-Founder, KiwiStays
nymisha@kiwistays.in`,
    notes: 'P1 — highest priority. He says "DM me, happy to chat." cal.com/arjun-vaidya-lec0j0 for booking. Follow up in 5 days if no reply.',
    updated: Date.now()-500
  },
  {
    investor: 'Neetan Chopra — IndiGo Ventures',
    channel: 'LinkedIn DM',
    status: 'Ready',
    subject: '',
    body: `Hi Neetan,

IndiGo flies 100M+ passengers a year to Goa, Dehradun, Manali, Coorg. What happens after they land? Most book unmanaged stays with zero quality guarantee and no brand they trust.

I'm Nymisha — CA, IIM-B, co-founder of KiwiStays. We manage premium vacation rentals at ₹1K-4K/night across leisure destinations. 61 properties, 78% occupancy, 85% five-star reviews. The trust layer that doesn't exist between "I booked my flight" and "I checked into my stay."

IndiGo Ventures has an explicit hospitality mandate with fresh capital. We'd love to explore what a KiwiStays × IndiGo distribution partnership could look like — the investment case and the strategic case are the same conversation.

Happy to share a deck or jump on a call at your convenience.

Nymisha Puvvada
Co-Founder, KiwiStays
nymisha@kiwistays.in`,
    notes: 'P1 — Also email neetan via GoIndiGoVentures.com application. InterGlobe parent invested in Treebo (Apr 2025) — hospitality thesis confirmed.',
    updated: Date.now()-1000
  },
  {
    investor: 'Rahil Dutt — IndiGo Ventures',
    channel: 'LinkedIn DM',
    status: 'Ready',
    subject: '',
    body: `Hi Rahil,

Thanks for connecting! I'm Nymisha — CA, IIM-B, co-founder of KiwiStays. We manage vacation rentals at ₹1K–4K/night across leisure destinations — 61 properties, 78% occupancy, EBITDA-positive, bootstrapped. AI-driven ops give us a structural cost advantage that luxury PMCs can't replicate at their price point.

Raising ₹10Cr Pre-Series A. Would love to share a deck and get 20 minutes if this fits your hospitality thesis.`,
    notes: 'P1 — Rahil is Lead, Investments at IndiGo Ventures. ISB + SRCC, ex-Citi. He runs deal evaluation for Neetan Chopra. Send alongside or before the Neetan message.',
    updated: Date.now()-2000
  }
];
